### ISSUE TITLE
A "Course" Could be even easier to author

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#102]
Currently, a course is a static HTML page...

However, it essentially looks like a topic page, maybe that's an option?
-- It just needs new CSS.

At the very least, instead of using a div we should have a list of divs. That we can have each line numbered with CSS so if we re-order a course, or insert a new page, the numbering can change.

**Comment by xtitter** [comment]
It would be nice to have some course specific styling or tooling ala topics.  At one point we thought we could generalize some of Dan's stuff he uses for CS10 -- the dynamic calendar, etc.

**Comment by cycomachead** [comment]
oh yeah, calendaring is a project I want to work on... haha.

I'm gonna work on re-doing the course HTML page to make moving topics around easier. :)

**Comment by peterasujan** [comment]
We can definitely do that. There is already a course.js file, which could do some processing if needed, or we could do it all in CSS. Speaking of which, the colossal monster that is BJC.css could use some serious examination...

**Comment by cycomachead** [comment]
Closing because this belongs in llab and it's not going to happen immediately.
