### ISSUE TITLE
Should have a quiz category for topic pages.

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#103]
It would be nice if a quiz had a different icon than the standard resource did. (Ideally, something which suggests that it's a quiz.)

**Comment by peterasujan** [comment]
There actually is one (BJC.css line 913). I think people just haven't been using it in topic files.

**Comment by cycomachead** [comment]
This is there now, and it works, right?

**Comment by peterasujan** [comment]
Yes. It'll be a relatively easy task to go through all of the topic pages and change them.

**Comment by ghost** [comment]
Hello, could we modify the "check if" block to make sure people don't confuse the assignments . One is a number ,and so I guess the input space should be circular.

**Comment by ghost** [comment]
Hello, could we modify the "check if" block to make sure people don't
confuse the assignments . One is a number ,and so I guess the input space
should be circular.
