### ISSUE TITLE
Lab 12 ("Recursive Reporters") Comments

### ISSUE THREAD

**Issue by peterasujan** [cs10/bjc-r#112]
Please post lab 12 comments here.

**Comment by rachelhuang072** [comment]
In recursive-reporters.topic&step=0: 
The image <img src="/bjc-r/img/recur/reporters/list->sentence.png" alt="list->sentence"> does not show up.

**Comment by rachelhuang072** [comment]
In recursive-reporters.topic&step=7:
Should the quiz be interactive or is it just for them to think about?

**Comment by rachelhuang072** [comment]
In recursive-reporters.topic&step=17:
The sentence after the even numbers code image: The green Operatots blocks above take the remainder on dividing the first number by 2... Operatots should be Operators and on should be of.

**Comment by peterasujan** [comment]
Image fixed by @aaaschmitt.
"Operatots" type fixed by @paulirwin12.
