### ISSUE TITLE
Update the Wiki or bjc-authors.github.io on how to contribute

### ISSUE THREAD

**Issue by isharacomix** [cs10/bjc-r#12]
We need to outline:
- [ ] How teachers can use the resources in this repo
- [ ] How teachers can make their own copies of the repo and host them on github.io
- [ ] How teachers can push their changes upstream
- [ ] How to use the issue tracker for the technical team

**Comment by xtitter** [comment]
this stuff goes into the bjc-teachers-resources repo!
