### ISSUE TITLE
FloodFill Exercise Looks Odd

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#124]
http://bjc.eecs.berkeley.edu/bjc-r/cur/programming/recursion/applications/flood-fill.html?topic=original_bjc/15-recursion-III.topic&step=6&course=

**Comment by xtitter** [comment]
This program needs to be completely re-written, functionally, sheesh.

**Comment by cycomachead** [comment]
@xtitter I think the new flood fill works fine. Does it need to be integrated into a recursion lab?
