### ISSUE TITLE
Recursion Lab II Piglatin solution

### ISSUE THREAD

**Issue by ibirnam** [cs10/bjc-r#131]
This needs a fix, since it's incorrect. I've provided a solution below, can someone make the change?
![screen shot 2013-10-28 at 3 21 14 pm](https://f.cloud.github.com/assets/1196118/1424533/14d2e0ac-4020-11e3-9671-317eee394d54.png)

**Comment by cycomachead** [comment]
Thanks ian! Do you have the file saved from that solution, if not I can
re-create it.

## 

Michael Ball
http://www.michaelballphoto.com
Photos & iPhone Apps!

**Comment by ibirnam** [comment]
There ya go

On Mon, Oct 28, 2013 at 3:34 PM, Michael Ball notifications@github.comwrote:

> Thanks ian! Do you have the file saved from that solution, if not I can
> re-create it.
> 
> ## 
> 
> Michael Ball
> http://www.michaelballphoto.com
> Photos & iPhone Apps!
> 
> On Mon, Oct 28, 2013 at 3:27 PM, Ian Birnam notifications@github.comwrote:
> 
> > This needs a fix, since it's incorrect. I've provided a solution below,
> > can someone make the change?
> > [image: screen shot 2013-10-28 at 3 21 14 pm]<
> > https://f.cloud.github.com/assets/1196118/1424533/14d2e0ac-4020-11e3-9671-317eee394d54.png>
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/beautyjoy/bjc-r/issues/131>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/beautyjoy/bjc-r/issues/131#issuecomment-27263545
> .

## 

Ian Birnam
UC Berkeley Computer Science Undergrad
Cell: 510-552-9102

**Comment by cycomachead** [comment]
I think Github eats attachments. :(

Wanna send it to my gmail?

Thanks! :)

## 

Michael Ball
http://www.michaelballphoto.com
Photos & iPhone Apps!

**Comment by ibirnam** [comment]
sent

On Mon, Oct 28, 2013 at 3:46 PM, Michael Ball notifications@github.comwrote:

> I think Github eats attachments. :(
> 
> Wanna send it to my gmail?
> 
> Thanks! :)
> 
> ## 
> 
> Michael Ball
> http://www.michaelballphoto.com
> Photos & iPhone Apps!
> 
> On Mon, Oct 28, 2013 at 3:39 PM, Ian Birnam notifications@github.comwrote:
> 
> > There ya go
> > 
> > On Mon, Oct 28, 2013 at 3:34 PM, Michael Ball notifications@github.comwrote:
> > 
> > > Thanks ian! Do you have the file saved from that solution, if not I
> > > can
> > > re-create it.
> > > 
> > > ## 
> > > 
> > > Michael Ball
> > > http://www.michaelballphoto.com
> > > Photos & iPhone Apps!
> > > 
> > > On Mon, Oct 28, 2013 at 3:27 PM, Ian Birnam notifications@github.comwrote:
> > > 
> > > > This needs a fix, since it's incorrect. I've provided a solution
> > > > below,
> > > > can someone make the change?
> > > > [image: screen shot 2013-10-28 at 3 21 14 pm]<
> > 
> > https://f.cloud.github.com/assets/1196118/1424533/14d2e0ac-4020-11e3-9671-317eee394d54.png>
> > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/beautyjoy/bjc-r/issues/131>
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/beautyjoy/bjc-r/issues/131#issuecomment-27263545>
> > > .
> > 
> > ## 
> > 
> > Ian Birnam
> > UC Berkeley Computer Science Undergrad
> > Cell: 510-552-9102
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/beautyjoy/bjc-r/issues/131#issuecomment-27263882>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/beautyjoy/bjc-r/issues/131#issuecomment-27264309
> .

## 

Ian Birnam
UC Berkeley Computer Science Undergrad
Cell: 510-552-9102
