### ISSUE TITLE
Fixes for Lab 1

### ISSUE THREAD

**Issue by xtitter** [cs10/bjc-r#174]
p1 (welcome to snap)

p2 (overview of window)
- [ ] make image smaller

p3
- [ ] include screen shot of just the palette, rather than referring to "previous image" - fix the text.  Bold the names of the tabs ('motion')
- [ ] images of blocks are way too big.
- [ ] 'inline' images aren't styled right
- [ ] "The sprite is that arrowhead image in the middle of the stage" should go into the next to the last paragraph

p4 (scripts)
- [ ] "Try recreating the 'following script' ..." rather than "...'this' ..."
- [ ] words that get introduced for the first time should be italicized.  "that we call a <i>script</i>"
- [ ] "you will know if your script is running if 'it' has a highlighted border [] as in the image below"  (use pronoun 'it' and remove some text in the []
- [ ] this page should include that scripts run from top to bottom.  There is some text in the "reflections" page much later.

p5 (multiple sprites)
- [ ] image should be inline
- [ ] image should have more context
- [ ] maybe this page should move right before kaleidscope.  It just sits here weirdly.

p6 -
- [ ] lose the 'but gosh' paragraph.  Start page with "if you [] click..." paragraph (remove 'just' though.
- [ ] lose this page!  Why do costumes here? 

p7 (bossing sprites around)
- [ ] weird quote chars in 3rd para
- [ ] brian will fix text -- lots of weirdness

p8
- [ ] flush this

p9
- [ ] ??  flush this, or have them do something

p10 (sensor block)
- [ ]  brian sez lets call these reporters

p11
- [ ] we don't need this -- sequence of events as already been empahsized earlier, this doesn't add anything

BRIAN NEEDS MORE

**Comment by cycomachead** [comment]
- [ ] Clean up duplicate Images
- [ ] rm uneeded files, or move for safekeeping
- [ ] fix directory structure to be consistent

**Comment by xtitter** [comment]
We should change any refences to 'topic1' to 'welcome'. We don't want the directory structure to encode the particular sequence we are using.

**Comment by cycomachead** [comment]
Yeah, I was going to do that at some point, too.

...except changing 100 URLs at 3AM is guaranteed to give errors. :P

## 

Michael Ball
http://www.michaelballphoto.com
Photos & iPhone Apps!

**Comment by xtitter** [comment]
I'll let Gary Wright <a 
href="http://www.youtube.com/watch?v=n-DmAh0dObI">speak for me</a>.  
Somewhere in there is a lyric saying, essentially, "let a tool do the 
refactoring rather than doing it manually".

But, I guess it won't catch the .topic targets unfortunately. Another 
reason for topic sequences to become regular html.

Of course, I don't use dreamweaver myself, lol.

   <-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><->
   Nathaniel Titterton, Ph.D.                    nate@berkeley.edu
   Computer Science Education         U.C. Berkeley, 329 Soda Hall

**Comment by xtitter** [comment]
I made a refactoring of the files in /cur/ and /prog/ and fixed the wack capitalization stuff.

there are still some styling issues I'd like to address. 

I didn't deal with refactoring the stuff in /img.... ug.  Dreamweaver someday.

I'm closing this issue for now; though.   We can open another one with additional comments
