### ISSUE TITLE
Post-Receive Hooks

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#176]
Nate, 

What have you done to try to get a simple PHP hook running? I'd like to work on setting one up for CS10 and for bjc.berkeley.

**Comment by xtitter** [comment]
Basically nothing.  I got BJC.b.e to have php and python though, that took
3 months.

Nate fat-thumb Titterton

**Comment by cycomachead** [comment]
Hmm. Ok. I'll play around with this in a few weeks when things settle down
(hopefully).

## 

Michael Ball
http://www.michaelballphoto.com
Photos & iPhone Apps!

**Comment by cycomachead** [comment]
Just want to say I'm FINALLY making progress on this and will be able to make a hook work soon. I hope!

**Comment by xtitter** [comment]
can you explain what you mean by 'hook'?  lol

**Comment by cycomachead** [comment]
Do something on some event...

http://git-scm.com/book/en/Customizing-Git-Git-Hooks

GitHub supports sending POST Requests to a URL for all sorts of things, I'm gonna try one for a `push` event. (though, GitHub supports this notion of "deployments" which I'll take a look at later.)

There's some stuff here https://github.com/cs10/webhooks
Right now it's all python based, but I'd like to integrate it into an existing build system if possible. (Grunt, Puppet something else...?)

**Comment by cycomachead** [comment]
I have one hook running right now which updates the CS10 website! :)
