### ISSUE TITLE
Everyone: Please Make Git Case Sensitive

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#178]
It seems like theres a couple places where caps in URLs and inconsistencies are causing problems. 

Two things:
1. All lowercase urls are better if possible.
2. Make sure your computer is case sensitive. To fix it, do this in a terminal: (Definitely works for OS X, and should work for Git Shell. I think Ubuntu users don't need to do anything)

```
 git config --system core.ignorecase false
```

**Comment by xtitter** [comment]
This sucked. 

Lesson 1: always make all paths fully lowercase.

#2 never had two different paths that differ only by case.  If you are going to fix the case of something accidentally committed, make it distinct in addition to lowering the case.

**Comment by cycomachead** [comment]
:/

Yeah, the trick seems to be git mv ... tmp and then commit and them move
back.

## 

Michael Ball
http://www.michaelballphoto.com
Photos & iPhone Apps!
