### ISSUE TITLE
Lab 2 Issues and Fixes

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#181]
Please use this issue for lab 2 updates

**Comment by peterasujan** [comment]
In "Adding an input" (http://xtitter.github.io/bjc-r/cur/programming/functions/intro/adding-a-simple-input.html?topic=berkeley_bjc/intro_new/2-loops-variables.topic&step=8&course=), step 4 references script variables when AFAIK they haven't yet been taught.

**Comment by xtitter** [comment]
Oh good point.  We haven't even introduced the term "variable"yet ...  (Lab
3!). Gotta clean that up.

Nate fat-thumb Titterton

**Comment by vshi** [comment]
This is a really minor detail, but when the "for i = x to y" block is first introduced (http://inst.eecs.berkeley.edu/~cs10/labs/cur/programming/variables/for.html?topic=berkeley_bjc/intro/loops-variables-conditionals.topic&step=10&course=), it's not automatically in the Control palette, or at least it wasn't for me. They might have to go to "import tools" to get the block.

**Comment by cycomachead** [comment]
Yeah, they will always have to do that. The lab should instruct students to
import tools.

## 

Michael Ball
http://www.michaelballphoto.com
Photos & iPhone Apps!

**Comment by ibirnam** [comment]
everything seems ok, just wanted to bump Victoria and Peter's issues. have these been fixed?

**Comment by xtitter** [comment]
Fixing them now.

**Comment by jasnowiss** [comment]
For the 'Composing with "Buggy" Custom Blocks' quiz, the answer for question 2 does not match what the code does. It would only yield this answer if you replace all instances of 'draw square %size' with 'draw square %size BUGGY', and if the sprite starts the script facing upwards.

**Comment by xtitter** [comment]
thanks.  All of these issues are now fixed (in this repo), I believe.

**Comment by Gubolin** [comment]
(I hope this is the right issue - you should clean them up and change the titles to "Topic 2 Feedback: Loops and Building your own Blocks")

In "Bug Dance!", the costumes should have a transparent background. At the moment there is a white square around it that interferes with pen trails or the stage's costume.

(Edit) Also, the demonstration blocks should not be snapped together. Students tend to ignore their task and build custom blocks like "dance 4 times" and so on...

**Comment by cycomachead** [comment]
> (I hope this is the right issue - you should clean them up and change the titles to "Topic 2 Feedback: Loops and Building your own Blocks")

It's usually best to file new issues. We have a lot of older threads from various discussions that happened in the past.

> In "Bug Dance!", the costumes should have a transparent background. At the moment there is a white square around it that interferes with pen trails or the stage's costume.

Yeah, I can fix those. 

> (Edit) Also, the demonstration blocks should not be snapped together. Students tend to ignore their task and build custom blocks like "dance 4 times" and so on...

I think the script is OK because it gives students a quick example to play with. If they completely ignore it and create something different, that's fine.
