### ISSUE TITLE
Your first custom block

### ISSUE THREAD

**Issue by brianharvey** [cs10/bjc-r#190]
The paragraph numbered 3 skips a step, namely typing the block name into the text box.  So this should be broken into two pieces.

Somewhere it should say that the steps (color, name, shape, scope) can be done in any order but that it's a good idea to get into the habit of going top to bottom in the dialog to be sure not to skip a step.

This page doesn't mention the scope choice.  I think it's fine to say "you're almost never going to change this from the default, so don't worry about it" but I wouldn't omit it altogether.

In steps 1-4 the block is called "draw-square" with a hyphen, but in steps 5-6 it's called "draw square" as two words (including the pictures).

**Comment by xtitter** [comment]
I also don't like the term "prototype" --- i think 'title' is clearer.

**Comment by brianharvey** [comment]
But it's not really the title; it's the title plus the formal parameters.  Iirc we spent quite a while coming up with bad ideas about what to call it before deciding on "prototype," which is meant to convey that the actual block ('s shape, color, title text, input slots -- what it looks like in the palette) is based on it.

**Comment by xtitter** [comment]
That makes sense.  arg.  I am soooooo tired of this page.  I'm going to not introduce the term 'prototype' in this page, deciding that it is too early for these poor students.  A term for topic 4.

**Comment by xtitter** [comment]
Closing, but the picture in step 4 still says "draw-square".
