### ISSUE TITLE
Talking about keeping clutter out of blocks

### ISSUE THREAD

**Issue by brianharvey** [cs10/bjc-r#192]
I should have mentioned this in the "your first block" lesson.

I think it's important to tell students /not/ to put things like PEN DOWN or an initial position/direction adjustment in their block definitions, explained by showing a script like
REPEAT 8
   DRAW SQUARE
   RIGHT 45
and, first, getting them to exclaim over the interestingness of the picture, and then, crucially, getting them to see that you couldn't use squares as pieces of a bigger picture if you pin them down.  That sort of housekeeping should be done in a top-level script.

**Comment by xtitter** [comment]
This gets addressed directly in the "composing with buggy blocks" activity, no?

**Comment by brianharvey** [comment]
I haven't gotten that far yet, but if so, it's too late.  I always have to fight with students about not putting PEN DOWN in their square procedures.  Let's nip that bad habit in the bud.

**Comment by xtitter** [comment]
I think this is a pretty subtle issue, with understanding to be refined over repeated exposures.  I could add a sentence in the already way too complicated "your first block" page, I guess.  

What would be best, though, is to think up more self-tests and activities that help them understand where stuff goes in the various levels of abstraction, and to include them in topics 2, 3, and certainly 4.

**Comment by brianharvey** [comment]
Feel free to add a whole page just after "your first block" /titled/ "Keeping clutter out of your blocks."  That would avoid lengthening the former, and I think the point is important enough for its own page anyway.
