### ISSUE TITLE
We now have duplicate topics 1 folders! 

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#199]
So, what if I rm' d the capitalized ones and then ignored them, so that they can't pop back up ever?

The lowercase ones seem to be just fine.

**Comment by xtitter** [comment]
I think I killed this dead -- deleting these from github's own web interface.  I hope.  

(Note -- all "topic1"X is supposed to be orphaned and deletable, except in /img.  It would be nice to have a tool refactor that for us automagically)
