### ISSUE TITLE
Number guessing using script vars for answer?

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#200]
Is it worth doing to enforce good habits?

**Comment by xtitter** [comment]
The solution? Absolutely.  Send the solutions for all three hwks to the
list, or me.  I can take a pass

Nate fat-thumb Titterton

**Comment by cycomachead** [comment]
Uh, I don't know if we have those, well, we do for #2 which is the most important.

I mostly meant the number guessing exercise in lab 3. Should we use the reporter ask, or at least use a script var?

**Comment by aaaschmitt** [comment]
@cycomachead I think the exercise looks fine as is.  I'll let you close this if you want or if you really think it needs to be changed post a follow up here and I can get someone to do it.

**Comment by cycomachead** [comment]
If the current image still doesn't have a script var we should change it.

**Comment by aaaschmitt** [comment]
do you mean a script var to hold answer? there is one that holds the secret number, but not answer.  I guess it would be good practice to use one...but idk might just make it more cluttered. Here's the page: https://inst.eecs.berkeley.edu/~cs10/labs/cur/programming/conditionals/number-guessing-game-v1-0.html?topic=berkeley_bjc/intro_new/3-conditionals.topic&step=14&novideo=true&noreading=true&noassingment=true&course=cs10_fa14.html

**Comment by cycomachead** [comment]
Eh, I guess that's fine. It might have been improved since this was filed...

**Comment by cycomachead** [comment]
At some point we should introduce a reporter answer block..but thats a separate issue.
