### ISSUE TITLE
edX Quiz Specs

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#216]
For reference, I don't know if it's worth considering making ours easier to convert?

http://ca.readthedocs.org/en/latest/common_problems.html

**Comment by xtitter** [comment]
link is broken?

**Comment by cycomachead** [comment]
Yeah. Not sure where they went. 

Anyway I've got a better way to do quizzes. I think...

## 

Michael Ball
From my iPhone
http://michaelballphoto.com
