### ISSUE TITLE
(Minor) Icon for Video resources makes no sense

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#225]
See here: 
http://bjc.eecs.berkeley.edu/bjc-r/topic/topic.html?topic=berkeley_bjc/additional-videos-reading.topic&novideo=true&noreading=true&course=cs10_sp14.html

**Comment by aaaschmitt** [comment]
I mean, it's a collection of images I guess.....which is a video sort of...right? I have no idea.....

new icon proposal: http://findicons.com/search/video     

I like the third from the left, top row

**Comment by cycomachead** [comment]
Oh, that's not bad.

I also like: http://findicons.com/icon/58541/movies

I don't know what's the best...I just think this one is a bit odd. Lol.

**Comment by aaaschmitt** [comment]
I like that one.  I'll find someone to change it.

**Comment by aaaschmitt** [comment]
LOL just realized what this was titled....

**Comment by cycomachead** [comment]
> LOL just realized what this was titled....

Oops....
