### ISSUE TITLE
Titles for videos/reading are really really ugly

### ISSUE THREAD

**Issue by xtitter** [cs10/bjc-r#244]
Lots of html special chars in there

http://bjc.berkeley.edu/bjc-r/admin/empty-curriculum-page.html?src=http://inst.eecs.berkeley.edu/~cs10/sp12/readings/BtB5-pt1.pdf&topic=berkeley_bjc/areas/concurrency.topic&step=1&title=%20Blown%20to%20Bits:%20Chapter%205%20Part%201%20&noassigment=true&course=berkeley_bjc.html

**Comment by cycomachead** [comment]
These actually look fine to me...

**Comment by peterasujan** [comment]
This seems to only happen some of the time... I think I fixed it though.
