### ISSUE TITLE
Auto refresh when a lab page doesn't load

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#248]
So this came to me in the middle of the night and might not be the best idea...

But I was thinking we should have some way of recovering from whatever weird events happen to cause done lab pages to not load the first time. Maybe we could add a time that tries to trigger a page refresh or loading of the page in the URL? I'm not sure how hard it would be...

Gosh, is Bjc what keeps me up at night? :P

**Comment by xtitter** [comment]
Is there a way I can reproduce the done lab page not loading thing?

   <-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><->
   Nathaniel Titterton, Ph.D.                    nate@berkeley.edu
   Computer Science Education         U.C. Berkeley, 329 Soda Hall

**Comment by cycomachead** [comment]
Hmm, not sure there's a reliable way...perhaps an unreliable connection?

The error is on urls like this page I think...
http://bjc.berkeley.edu/bjc-r/topic/topic.html?topic=berkeley_bjc/lists/lists-I.topi&novideo=true&noreading=true&noassignment=true&course=cs10_sp14.html

(I made the bad url on purpose...)

**Comment by cycomachead** [comment]
This issue was moved to beautyjoy/llab#92
