### ISSUE TITLE
Google analytics?

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#249]
Can we use them?

I can fix this pretty easily...

**Comment by cycomachead** [comment]
@peterasujan @xtitter 
Hey do we have any objects to this?

Or should we start building a simple way of creating logs for activity tracking? I'd like some browser stats + students progress if possible.

**Comment by peterasujan** [comment]
I have no problem with this.

I think it'd be interesting to explore what we could do as far as saving our own data to some server from within quiz/curriculum/topic.js

**Comment by cycomachead** [comment]
I'll work on GA and then I'll draft a new issue about the idea of student progress tacking...
