### ISSUE TITLE
Fix `ul > ul` in CSS

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#255]
No nested boxes!

**Comment by peterasujan** [comment]
Off the top of you head, do you know where there's an example of this?

**Comment by cycomachead** [comment]
Uh, yes, but I forget the page in lab content where it happens. There's a few places. I'll tackle this one today.

**Comment by peterasujan** [comment]
K cool. By the way, I already half dealt with this [here](https://github.com/beautyjoy/bjc-r/blob/gh-pages/admin/BJC.css#L241), so you may just need to add to it.

**Comment by cycomachead** [comment]
Ok, I'll take a look. The border was occurring around the entire nested list, so I'll have to see if this takes care of that.

Now to peruse the labs!

**Comment by cycomachead** [comment]
I'm going to close these because I found this page which seems that the issue has been fixed.
https://inst.eecs.berkeley.edu/~cs10/labs/cur/programming/concurrency/snap/read-and-finish-with-n-answer-snap.html?topic=berkeley_bjc/areas/concurrency.topic&step=12&novideo=true&noreading=true&noassignment=true&course=cs10_sp14.html

**Comment by xtitter** [comment]
nice

   <-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><->
   Nathaniel Titterton, Ph.D.                    nate@berkeley.edu
   Computer Science Education         U.C. Berkeley, 329 Soda Hall
