### ISSUE TITLE
Sum Things Up: Images Different than Snap code

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#263]
https://inst.eecs.berkeley.edu/~cs10/labs/cur/programming/loops/sum-things-up-debug.html?topic=berkeley_bjc/intro_new/4-abstraction-testing.topic&step=3&novideo=true&noreading=true&noassignment=true&course=cs10_sp14.html

See this. Also, we don't need /3/ links... We should have just one.

**Comment by aaaschmitt** [comment]
fixed images and now there's just a single link wrapped around all of the images to reduce confusion.
