### ISSUE TITLE
Tools needed for the if - pause all block

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#264]
https://inst.eecs.berkeley.edu/~cs10/labs/cur/programming/debugging/the-check-block.html?topic=berkeley_bjc/intro_new/4-abstraction-testing.topic&step=6&novideo=true&noreading=true&noassignment=true&course=cs10_sp14.html

The text should clearly mention the block comes from importing tools.

**Comment by aaaschmitt** [comment]
fixed. added a bolded sentence just before the description of how the block works.
