### ISSUE TITLE
Weird Characters on this page

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#265]
https://inst.eecs.berkeley.edu/~cs10/labs/cur/programming/lists/hof/combining-all-the-items-of-a-list.html?topic=berkeley_bjc/lists/lists-I.topic&step=4&novideo=true&noreading=true&noassignment=true&course=cs10_sp14.html

**Comment by cycomachead** [comment]
Here too:
http://0.0.0.0:8000/bjc-r/cur/programming/intro/snap/exploring-snap-scripts.html?topic=berkeley_bjc/intro_new/1-introduction.topic&step=3&novideo=true&noreading=true&noassignment=true&course=cs10_sp14.html

**Comment by aaaschmitt** [comment]
fixed both will push soon.
