### ISSUE TITLE
Newline needed on this page below list

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#268]
https://inst.eecs.berkeley.edu/~cs10/labs/cur/programming/algorithms/everyones-got-algorithms.html?topic=berkeley_bjc/areas/algorithms.topic&step=0&novideo=true&noreading=true&noassignment=true&course=cs10_sp14.html

(Another minor issue I'm filing as I'm just going through stuff.)

**Comment by cycomachead** [comment]
Oops. I think I meant, a line break... As in 
<br /> 

:/
The content looks weird under the list...

**Comment by xtitter** [comment]
https://beautyjoy.github.io/bjc-r/cur/programming/algorithms/everyones-got-algorithms.html?topic=berkeley_bjc/areas/algorithms.topic&step=0&novideo=true&noreading=true&noassignment=true&course=cs10_sp14.html

looks fine to me?  Anyway, do what you will

**Comment by cycomachead** [comment]
Oh wait. I was looking at the wrong link... 

Yep it's good. 

## 

Michael Ball
From my iPhone
http://michaelballphoto.com
