### ISSUE TITLE
bjc.processLinks should share code with bjc-topic.js

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#271]
There's lots of room for refactoring here.

**Comment by peterasujan** [comment]
I'm thinking about working on this and #272 together. Or is a lot already happening here in #270?

**Comment by cycomachead** [comment]
Uh, 270 takes care of a bit, but not much. I haven't really touched bjc-topic, but I've changed a ton in bjc course.

**Comment by cycomachead** [comment]
@peterasujan Closing this because of llab stuffs but we should work on this soon. :)
