### ISSUE TITLE
Link to Main Labs List when working on a lab?

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#28]
Currently, unless I'm missing something, there's no way to jump to the list of all labs for a course.

For instance, on this page (mid lab 2):
http://bjc.berkeley.edu/bjc-r/cur/programming/variables/nested-for.html?topic=berkeley_bjc/intro/loops-variables-conditionals.topic&step=11
I can jump to the main lab 2 page: 
http://bjc.berkeley.edu/bjc-r/topic/topic.html?topic=berkeley_bjc/intro/loops-variables-conditionals.topic
But It would be very handy to have an easy way to jump to all labs pages, here:
http://bjc.berkeley.edu/bjc-r/course/berkeley_bjc.html

**Comment by xtitter** [comment]
A good idea. (I don't think it will be very important for students in practice, who will be working off a single course / url for a whole semester or year).

But, it shouldn't be too hard to add. I'm thinking:

add a class "bjc-course" onto the body tag of course pages in the repo; 
add something to bjc-curriculum.js (which I think is run in those files?) which, for pages with that class, tweaks all links to include a course url parameter with a value of the course location
add something to topic.js that, if the course parameter is present, puts a link to it at the top of topic.html.

**Comment by cycomachead** [comment]
In the past, I've often jumped between labs in moodle when working with students, especially later in the semester when you want to look of past labs as reference.

**Comment by xtitter** [comment]
Peter, I'm going to "assign" this to you -- when you have some free time, it should mimic the stuff you did with novideos=true somewhat
