### ISSUE TITLE
Removing YouTube videos from Fa13 CS10 Labs

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#30]
The current set of labs has lecture videos embedded within each lab. Should these be removed for students who are taking the class in person?

It's not strictly necessary, but might be  worth considering.

**Comment by xtitter** [comment]
Peter's new feature could enable this, from https://github.com/beautyjoy/bjc-r/commit/020023ce2dc882f9babe705da322b5a9e5d8baf4
(I admit to not testing though!)

it would require a different course page for CS10, not berkeley_bjc.html....  or rather, referring to the standard course with a .../course/berkeley_bjc.html&novideo=true  or something

It isn't a bad idea to separate the course files for cs10 and high school bjc...

**Comment by cycomachead** [comment]
Yeah, I saw.

I'm going to look over some things tonight and on the weekend, but I'm thinking we should just create a 'CS10' brach for labs and host it on the CS10 site.

Maybe we could even setup some git hooks to do auto-pushing which we push to github
