### ISSUE TITLE
Nav bar is ugly again...

### ISSUE THREAD

**Issue by peterasujan** [cs10/bjc-r#307]
It looks like some of the bootstrap files got merged in, and some (still necessary until we merge #270) jquery ui files got deleted

**Comment by cycomachead** [comment]
Ugh, I need to just finish this painful redesign process. WTF was I thinking? So much CSS to tweak and test!

**Comment by xtitter** [comment]
I, for one, have complete faith in you guys!

On Tue, May 27, 2014 at 10:50 PM, Michael Ball notifications@github.com
wrote:

> Ugh, I need to just finish this painful redesign process. WTF was I
> thinking? So much CSS to tweak and test!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/beautyjoy/bjc-r/issues/307#issuecomment-44368157.

## 

  <-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><->
  Nathaniel Titterton, Ph.D.                    nate@berkeley.edu
  Computer Science Education         U.C. Berkeley, 329 Soda Hall

**Comment by cycomachead** [comment]
Fixed finally! :)
:shipit:
