### ISSUE TITLE
don't include protocol (http) in javascript files 

### ISSUE THREAD

**Issue by xtitter** [cs10/bjc-r#311]
https:// loaded pages won't load http:// links, and things get broken because of that

**Comment by cycomachead** [comment]
So, if we do this, localhost stuff gets broken.

**Comment by xtitter** [comment]
why/how?

**Comment by cycomachead** [comment]
Actually, I don't know what I was thinking when I wrote that. Localhost is fine, it's the darn file:// that isn't... But that's OK. Also, we've fixed them all with LLAB right?

**Comment by xtitter** [comment]
yeah, no more file:// .  Wait, when did llab have any file:// ?

**Comment by cycomachead** [comment]
No, because we needed doc root to work, so there was never a use case for it.
