### ISSUE TITLE
Should the drop down menu show section titles?

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#329]
...the dropdown for in-lab nav. The "sections" on a topic page aren't used anywhere els, but it seems like they have some value / worth as a pacing and cognitive guide.

Maybe I'm overthinking this...

**Comment by xtitter** [comment]
They should; mike Clancy just noted this as well

**Comment by cycomachead** [comment]
Ok, cool. I've got an implementation idea... I'll work on it sometime this summer.

The question is -- should they link anywhere?

**Comment by cycomachead** [comment]
This issue was moved to beautyjoy/llab#94
