### ISSUE TITLE
Step 6: Topic 1

### ISSUE THREAD

**Issue by sean-morris** [cs10/bjc-r#33]
http://bjc.eecs.berkeley.edu/bjc-r/cur/programming/intro/snap/intro-play.html?topic=berkeley_bjc/intro/broadcast-animations-music.topic&step=6

The "Hint" at the bottom includes a scratch image. It needs to be replaced with a Snap! image.

**Comment by cycomachead** [comment]
Will be fixed in pull request #32

**Comment by xtitter** [comment]
I fixed this step, making far more changes to it than I started out wanting to do!  Can someone check it out and approve?   I'll push it over afterwards

http://xtitter.github.io/bjc-r/cur/programming/intro/snap/intro-play.html

**Comment by cycomachead** [comment]
I think it looks good!

**Comment by xtitter** [comment]
Which one?  Did you merge, or are you saying my version is ok?

**Comment by cycomachead** [comment]
Just saying it was OK. I don't think I could merge it myself, since I don't have the power to approve pull requests.
