### ISSUE TITLE
Clean up topics 16/17

### ISSUE THREAD

**Issue by xtitter** [cs10/bjc-r#334]
Maybe these are fixed in ~cs10, but they aren't in bjc-r!  Can someone push from cs10 back to here if so?  Or, what should we do with all the fixme and ABCD stuff?

**Comment by cycomachead** [comment]
Are these Python?

If so they aren't fixed anywhere. 

All python stuff needs a major re-work.

**Comment by xtitter** [comment]
we should rip it out, then -- its sitting there in our "latest greatest BJC!" course...
