### ISSUE TITLE
Move to HTML 5 doctype

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#34]
Can we switch to HTML 5 doctypes? Not too much specific need for a change now, but it's always good to try to follow standards. :)

**Comment by xtitter** [comment]
Does every page need changing, or could it be added via bjc-loader.js?

**Comment by cycomachead** [comment]
I was taking a look, most of pages which are generated from JS, I could just change the base html file.

Otherwise, the only way I know of would be to do a find and replace on all of the content files, which is still easy. I can submit all the fixes in a pull request.

**Comment by cycomachead** [comment]
Assigning to me. I'll knock out all (or almost all) files in the next day and submit as 1 pull request.
