### ISSUE TITLE
Content Prioritization

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#349]
@xtitter @peterasujan @ddgarcia @brianharvey 

So we have a long list of serenity 1 issues -- we should see what we should fix before the fall and what the biggest issues teachers are having. 
Issues list: 
https://github.com/beautyjoy/bjc-r/issues?labels=severity%3A+1+%28immediate%29&page=1&state=open

My votes:
- Lists 1
- Python
- Paired Programming

**Comment by galacticmonkeys** [comment]
+1 for lists 1
