### ISSUE TITLE
Switch to a Markdown/Textile parser?

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#35]
This would be a longer from project, but what do you guys think of the possibility of using a markdown processor? It could make the process of writing and updating labs much quicker in the future, and easier for others to submit and find fixes.

**Comment by xtitter** [comment]
That was a thought when we moved to github, sure.  IIRC, it wouldn't prove any problem when viewed at http://beautyjoy.github.io/bjc-r/, or any fork's github page, but we would need a build process to have http://bjc.berkeley.edu/bjc-r/ work correctly.  (right now we just do a simple 'git pull' on bjc.berkeley.edu.

bjc.berkeley.edu is an ancient solaris box, iirc.  What is the markdown->html processor?

**Comment by cycomachead** [comment]
Yeah, I think the most common, and probably best way is to use a processor for the conversion. There's good python, ruby, PHP, and the original Perl script which can be run. In terms of build, we'd also have the issues for personal testing. (In terms of the server, it would be really simple to write a simple bash function which anyone with server access could run to update labs).

However, there is the possibility of doing processing client-side with a JS library, like this one: https://github.com/coreyti/showdown I've never tried it, but it looks interesting.

**Comment by peterasujan** [comment]
We could also do the build process on another computer, then push that over to bjc.berkeley.

**Comment by cycomachead** [comment]
I'm gonna close this for now, since we're moving to LLAB.
