### ISSUE TITLE
"Optional for Hotshots" :( 

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#350]
http://inst.eecs.berkeley.edu/~cs10/labs/cur/programming/recur/recursive-reporters/subsets-of-a-set-fast-soln.html?topic=berkeley_bjc/recur/recursive-reporters.topic&step=13&novideo=true&noreading=true&noassignment=true&course=cs10_sp14.html

This just needs to be fixed...

**Comment by peterasujan** [comment]
Sadly, my line of sed did not cover synonyms :P

**Comment by cycomachead** [comment]
:laughing:

**Comment by aaaschmitt** [comment]
Changed to: "Optional Challenge Activity"

**Comment by cycomachead** [comment]
The "Official" wording I believe is "Extra for Experience" but it doesn't matter too much. :)
