### ISSUE TITLE
Quiz Submit Button doesn't Work on "Ways to Broadcast" Test

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#38]
/bjc-r/cur/programming/intro/snap/diffways.html?topic=berkeley_bjc/intro/broadcast-animations-music.topic&step=8

Nothing happens for me, or for students, when I click the "Submit" button at the bottom of lab.

**Comment by xtitter** [comment]
Basically, all the quizzes that have form submissions need to be converted to the new quiz style.  This also means feedback for each answer needs to be added, in most cases.

**Comment by cycomachead** [comment]
Where should I look for places to add feedback and move them to the new format? 

(I just need an example of a working quiz and I can probably figure it out from there.)

**Comment by xtitter** [comment]
Check out the fixed up step:  http://xtitter.github.io/bjc-r/cur/programming/intro/snap/different-ways-to-broadcast.html?topic=berkeley_bjc/intro/broadcast-animations-music.topic&step=8

Tell me if its ok, and I'll push it over.  Also, can you use it as an example (and the step before it) on how to reformat the "form-based" stuff that brian did to the newer assessment stuff Peter and I have been working on?
