### ISSUE TITLE
Leslie's Moodle Fixes

### ISSUE THREAD

**Issue by isharacomix** [cs10/bjc-r#4]
@lpkeller needs to update some lab information for her version of the course on NC State's moodle.
- [x] Lab 5's source code doesn't match up with the lab write-up. Either resources need to be changed, or it needs to be made explicit that the code will not match for pedagogical reasons (ie, code literacy is a learning objective)
- [ ] "Try It" exercises need to be added to the unit on Lists.
- [ ] Add some algorithms to the noodle

**Comment by lpkeller** [comment]
Labs 4&5 are updated
