### ISSUE TITLE
Convert TOPIC 2 assessments from Brian's form style to the new style

### ISSUE THREAD

**Issue by xtitter** [cs10/bjc-r#40]
(michael -- I'm assigning you to this so we don't step on eachothers toes...  tell me if you don't want to tackle it)

We're basically done with topic 1, but there are three activities in topic 2 that need to be converted:
- test yourself: total turning
- test yourself: repeat
- if: what would you expect

Use the layout in the two quizzes in topic 1 to help!  You are going to need to convert to multiple choice, since that is currently the only kind of assessment item we have.  Other types coming soon!

**Comment by cycomachead** [comment]
Did we make these fixes?

**Comment by cycomachead** [comment]
I believe these questions have all been converted, at least in newer labs.
