### ISSUE TITLE
Feedback: Sprites: Reporters (1-introduction)

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#454]
#### [View the Page here](https://inst.eecs.berkeley.edu/~cs10/labs/cur/programming/intro/sprites/sprites-reporters.html?topic=berkeley_bjc%2Fintro_new%2F1-introduction.topic&novideo=true&noreading=true&noassignment=true&course=cs10_fa14.html&step=4)

---

What's up the "6...." at the title of this page? It doesn't need to be there, I think.

**Comment by aaaschmitt** [comment]
fixed.
