### ISSUE TITLE
Run, launch, call - wrong input will freeze the blocks

### ISSUE THREAD

**Issue by itssumertime** [cs10/bjc-r#473]
If you pass in a reported into "run" which actually takes in a command block, it turns red for indicating that the wrong type was passed in, but then you cannot click "stop" or anything to make the red go away and no other blocks can be clicked. 

Of course it makes sense that you should only pass in the correct types but I think the failure should be handled differently because this has made code freeze for some students and they had to exit Snap completely, which sucks if you didn't save your work.

**Comment by aaaschmitt** [comment]
do you have an example script? I wasn't able to reproduce the freezing
error with a multiply or join reporter block that was dropped into run.  In
fact it only seemed to give me an error if I did not ringify the function
and in this case I was still able to stop it with the stop sign.

Andy

**Comment by cycomachead** [comment]
This belongs in Snap<i>!</i>, but there are quite a few cases, I think. An empty input to launch freezes Snap<i>!</i>, IIRC. 

https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues

**Comment by cycomachead** [comment]
See the first two here:
https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues?q=is%3Aissue+is%3Aopen+freeze

Launch with no input does what Sumer describes. Things appear to be OK for a second, but then nothing works.

**Comment by aaaschmitt** [comment]
I see. But this does appear to be a problem only with launch not with run in the basic tests that I've tried. Either way it's a problem for the snap guys to handle.

**Comment by itssumertime** [comment]
Oops sorry, I didn't realize there was also the Snap issues page. I ran "pick random" inside of "run" and this time I could stop it but then I could drag only one or two more blocks out and then could not click them and subsequently could not move anything else on the screen. But yes, it's a Snap issue.
