### ISSUE TITLE
Quiz Buttons are Hard to Read

### ISSUE THREAD

**Issue by sean-morris** [cs10/bjc-r#50]
http://bjc.eecs.berkeley.edu/bjc-r/cur/programming/intro/drawing/turning.html?topic=berkeley_bjc/intro/loops-variables-conditionals.topic&step=2&novideo=true&noreading=true

The submit button is not readable. On click, you can see it but otherwise it looks like an empty box. I am using Chrome.

**Comment by cycomachead** [comment]
Agreed that submit buttons currently look a little weird.

What if I make them look a bit like bootstrap buttons?
http://getbootstrap.com/css/#buttons

**Comment by sean-morris** [comment]
Are we using bootstrap across the board? We should find a library we like
for menus and buttons and use it consistently. Bootstrap is good, jquery ui
is also good.

**Comment by cycomachead** [comment]
We do have jQuery UI which I can explore some more.

But I was mostly going to mimic the design up BS3 buttons w/o using the entire library. (Since that's a lot of data for only a couple classes.)

**Comment by sean-morris** [comment]
It isn't huge deal; I have found myself in look and feel hell when I
started mixing the libraries for things like menu's and buttons.

It is all you. I can't tell you guys how good it feels to be out of moodle
and linking directly to the files myself. Everything looks so clean.

**Comment by peterasujan** [comment]
We shouldn't worry too much about the styling of these form-style quizzes, because they're going away soon.
