### ISSUE TITLE
Feedback: Choosing some items from a list (lists-I)

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#506]
#### [View the Page here](http://bjc.berkeley.edu/bjc-r/cur/programming/lists/hof/choosing-some-items-from-a-list.html?topic=berkeley_bjc%2Flists%2Flists-I.topic&course=&step=6)

---

[ Edited: Because some people just have rage... ]

**Comment by aaaschmitt** [comment]
@cycomachead hahahahaha wtf is this......

**Comment by cycomachead** [comment]
LOL. Well , there's the downside of an open feedback button.... :/

Perhaps I ought to filter for poor language.
