### ISSUE TITLE
Lab 1: If used before explanation

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#53]
This page uses the if block without much intro to how it works.
http://bjc.eecs.berkeley.edu/bjc-r/cur/programming/intro/drawing/game-of-tag.html?topic=berkeley_bjc/intro/broadcast-animations-music.topic&step=11

And the quiz is based off repeat blocks without showing how they work: http://bjc.berkeley.edu/bjc-r/cur/programming/intro/drawing/testkeypress-soln.html

**Comment by xtitter** [comment]
Lab 1 is an interesting lab -- basically, it says "here is a bunch of stuff you can probably just figure on your own, but don't worry too much".  Then, lab2 starts from scratch and explains everything.

I don't mind lab 1, assuming that Brian knew what he was doing.  But, lab 2 just doesn't do enough to cover all the bases carefully and completely, even though that is its goal.  I think focus should be on fixing lab 2 up quite a bit, making it longer, etc.

**Comment by cycomachead** [comment]
Yeah, it's more of an interesting thought for discussion.

I was talking with other TA's and I was thinking lab 1 could be a little
more guided exploration by giving people a sample project with comments.
This is more of a longer discussion, but I think many students are missing
some very useful but not entirely intuitive pieces of Snap.

## 

Michael Ball
http://www.michaelballphoto.com
Photos & iPhone Apps!

**Comment by xtitter** [comment]
Closing, after we refactoring the b
