### ISSUE TITLE
mayaah

### ISSUE THREAD

**Issue by mayaah** [cs10/bjc-r#554]
Your Name: Maya Angelica Hernandez

Overview of Lab Comments: This lab is a great introduction to AI using a basic game that should be familiar to everyone. Maybe along with forks in the last slide of the lab add in something about game trees, though that might be too complex to explain. 

--- For each specific Issue (Copy this section as many times as necessary) ---
- [ ] Page Link: http://inst.eecs.berkeley.edu/~cs10/labs/cur/programming/lists/hof/ttt/04-triples2.html?topic=berkeley_bjc%2Flists%2Ftic-tac-toe.topic&course=cs10_sp15.html&novideo&noreading&noassignment
        Type of Issue: lack of clarity
        Severity: i.e. very minor inconvenience
        Comments: For the triples converter, maybe there's another block that can output a sentence but in the structure of a board so like:
  1ox
  4ox
  xxo
  Along with the triple converter so that visualizing the board can be easier? Or have it be an extra activity that students can challenge themselves to do to make debugging easier.

**Comment by cycomachead** [comment]
Please comment on the specifc thread for each lab. https://github.com/beautyjoy/bjc-r/issues/525
