### ISSUE TITLE
Early Labs: Quiz as HTML Form needs to be changed.

### ISSUE THREAD

**Issue by peterasujan** [cs10/bjc-r#62]
Example from Lab 1:
http://bjc.berkeley.edu/bjc-r/cur/programming/intro/drawing/testkeypress.html?topic=berkeley_bjc/intro/broadcast-animations-music.topic&step=10&novideo=true&noreading=true&nohomework=true

has not been converted to the proper quiz format.

**Comment by cycomachead** [comment]
Do we need to worry about the old labs still?

**Comment by peterasujan** [comment]
Most (if not all) of the relevant labs have been replaced, so I think we're good.
