### ISSUE TITLE
Incorrect Solution to Acronym Block in "Collecting Data into Lists" Lab

### ISSUE THREAD

**Issue by ibirnam** [cs10/bjc-r#65]
A student pointed out to me today that the solution for the Acronym block in Lab 5 (as shown here: http://tinyurl.com/BJCAcron) will include symbols such as '-', '+', etc. So for example, if you're phrase was "Beauty and Joy of + Computing", the block would return "BJ+C". Is this the desired effect? If not, the solution needs to be changed

**Comment by peterasujan** [comment]
I doubt this'll come up for very many students, and leaving it the way it is makes the code simpler. We can revisit this if it comes up again.
