### ISSUE TITLE
Recursion is a "Big Idea" for Lists 1 and 2 Labs

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#66]
Is this intended for BJC High School courses?

**Comment by xtitter** [comment]
I don't think so!  Lets go through these issues f2f tomorrow.

   <-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><->
   Nathaniel Titterton, Ph.D.                    nate@berkeley.edu
   Computer Science Education         U.C. Berkeley, 329 Soda Hall
