### ISSUE TITLE
Don't require rootURL ('bjc-r') in .topic file links

### ISSUE THREAD

**Issue by xtitter** [cs10/bjc-r#67]
the links in .topic files shouldn't need to start with /bjc-r/, but that should be prepended by topic.js using the 'rootURL' global.

Need to make this conditional for now, so that existing .topic file links that have the 'bjc-r' prepended don't break

**Comment by cycomachead** [comment]
I was planning on going through the repo.

Shouldn't the links just use '../' or however many directories they need to load fine?
