### ISSUE TITLE
Word fix in Lists 1

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#69]
The lab page for "When you really have to loop"
Says this:
"Why two different ways? Well, Brian likes the empty input slot, so it works the same as map and friends, but Dan likes the variable."

We probably shouldn't refer to people specifically since it just doesn't make sense if you don't know who Brian or Dan is.

**Comment by xtitter** [comment]
please review https://github.com/beautyjoy/bjc-r/pull/71
