### ISSUE TITLE
Algorithms Lab - global i

### ISSUE THREAD

**Issue by jcmack** [cs10/bjc-r#74]
The framework file declares an i as a global variable. I had one group try using a for loop. Needless to say, the for loop failed miserably. The i doesn't seem to be used and should be removed. 

http://snap.berkeley.edu/snapsource/snap.html#open:http://www.corsproxy.com/inst.eecs.berkeley.edu/~cs10/labs/prog/algorithms/algorithms-framework.xml

**Comment by cycomachead** [comment]
This is a problem with the imported BYOB files. 

I'll make a note to get this fixed soon! Hopefully :)
