### ISSUE TITLE
Algorithm Complexity Lab Bugs

### ISSUE THREAD

**Issue by ibirnam** [cs10/bjc-r#76]
1) The "Â" character is appearing everywhere throughout the lab, and I'm not sure what it's supposed to be.

2) On the "A (Non-Video) Game" page, the lab3 link doesn't link to the appropriate place. It takes you to some UCWise login page.

3) On the "Time is of the Es-sense" page, all the image links are broken.

4) On the "All the Numbers, All the Time" page, the framework link is a BYOB ypr file. This should be a Snap! framework.

5) On the "Logarithmic-Time" page, both links don't work, taking the user to some UCWise login page.

6) The final page of the lab is an outdated HW3 spec. This needs to be removed.

**Comment by jcmack** [comment]
7) Under activities it states "Use the BYOB timer to gather run time information". Should be Snap!

8) Minor but formatting is off on "Constant versus Linear" page.

**Comment by xtitter** [comment]
I'll take a look tonight

Nate fat-thumb Titterton

**Comment by cycomachead** [comment]
Lauren is also working on these.

**Comment by lmock** [comment]
Yep I've committed changes - waiting for their approval and the lab should be ok!

**Comment by xtitter** [comment]
you just changed the .topic file, though, right?  All the stuff in the 
lab pages themselves still needs to be done?

   <-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><->
   Nathaniel Titterton, Ph.D.                    nate@berkeley.edu
   Computer Science Education         U.C. Berkeley, 329 Soda Hall

**Comment by lmock** [comment]
No I was fixing lab activity pages themselves.

**Comment by cycomachead** [comment]
The latest pull request was lab 9. 

I approved 1 pull request which had all lab 8 fixes. We fixed the wording, images and snap files.

**Comment by xtitter** [comment]
sweet.  I you guys are happy, so am I, lol.

I'll push to bjc.berkeley.edu, fwiw
