### ISSUE TITLE
"Assignment" vs. "Homework" in .topic files.

### ISSUE THREAD

**Issue by peterasujan** [cs10/bjc-r#78]
We originally planned to use "assignment" as the tag for assignments in topics, but "homework" has been appearing quite a bit. There is currently no style for "homework." This should be added, or we should standardize to one or the other.

**Comment by xtitter** [comment]
homework is a fine tag -- for now, lets just have it look just like an assignment.

**Comment by peterasujan** [comment]
Okay, I'll update the CSS - should be a quick, one-line change.
