### ISSUE TITLE
"a.run" class for Snap! links not working properly for relative links.

### ISSUE THREAD

**Issue by peterasujan** [cs10/bjc-r#80]
The "run" class is currently being processed in bjc-curriculum.js using the bjc.getSnapRunURL function from bjc-library.js. This function is not properly handling relative links.

**Comment by cycomachead** [comment]
This is a high priority. We need to get easily runnable files.

**Comment by cycomachead** [comment]
*[x] Verify JS properly processes files with class run
*[] Verify CORS settings for various URLs
*[] Make sure target-new is set in CSS probably.
