### ISSUE TITLE
Concurrency Lab - Determinism.xml costumes don't show up

### ISSUE THREAD

**Issue by jcmack** [cs10/bjc-r#89]
In the Concurrency lab, there is a part on determinism:

This file doesn't work for me
http://inst.eecs.berkeley.edu/~cs10/labs/prog/Snap/Determinism.xml

Because 3 of the 4 costumes don't show up.

**Comment by aaaschmitt** [comment]
This does not appear to be an issue actually.  When I open the file white always wins since its deterministic.  However, once adding in the random wait time I see multiple colors.
