### ISSUE TITLE
Concurrency Lab - provided .xmls should automatically open in a new window

### ISSUE THREAD

**Issue by jcmack** [cs10/bjc-r#90]
Minor annoyance. Provided .xml framework and examples should automatically open in a new window

**Comment by cycomachead** [comment]
This is a current problem with the lab framework we are trying to fix. 

## 

Michael Ball
From my iPhone
http://michaelballphoto.com

**Comment by xtitter** [comment]
What is the issue?

**Comment by jcmack** [comment]
When you click on framework xml files in lab, they just open as a xml file instead of opening inside of Snap!. Not the end of the world, but not as user friendly.

**Comment by xtitter** [comment]
ah.  peter and I thought of a pretty easy solution to this, which he'll get to somepoint soon
