### ISSUE TITLE
Lab 10: Trees and Fractals Using Recursion

### ISSUE THREAD

**Issue by lmock** [cs10/bjc-r#97]
If anyone has any comments on this lab, please submit them here and we will try to get them fixed as soon as we can! Thank you!

**Comment by jcmack** [comment]
Remove "Make sure you watch the first recursion lecture (assigned last week) before doing this lab!" from Lab 10 main page.

**Comment by cycomachead** [comment]
Yeah, I was going to re-word to say make sure you've seen the lecture.

**Comment by jmca93** [comment]
Part1: "That's going to be really...we always want to be able to assume that our tree blocks leave the sprite in the same position, and facing the same direction, after it as before it." (the last part of the sentence is a little confusing! Maybe "after the recursion as before it"?)

Part3: Spelling error "There's a base case and a recursice case." <- should be "recursive"

Random Tree: Needs a comma "Unfortunately(,) our attempt..."

Base Cases: "Now that you have some experience with some recursion, we're going to point out some of the anatomy of a recursive procedure." (delete one of the "some"s, there are too many in that sentence.

Snowflake: Spelling error "(This makes the entire fractal the same ditance from left to right in every level.)" <- should be "distance"

**Comment by zmmachar** [comment]
In Part3: I think "What's the base case in the vee program?" should read "What's the base case in the tree program?"
